<#
.SYNOPSIS
    One-time GPU environment setup for building with CUDA (Windows).

.DESCRIPTION
    Finds cl.exe (MSVC C++ compiler) required by nvcc, then writes
    NVCC_CCBIN into src-tauri/.cargo/config.toml so that any terminal
    can compile with --features cuda without needing a VS Developer Prompt.

    The generated config.toml is machine-specific — do not commit it.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File setup-gpu-env.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=== Logo Studio — GPU build environment setup ===" -ForegroundColor Cyan
Write-Host ""

# ── 1. Find cl.exe ────────────────────────────────────────────────────────────

function Find-ClExe {
    # Try vswhere.exe (most reliable — ships with VS Installer)
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    if (Test-Path $vswhere) {
        $vsPath = & $vswhere -latest -property installationPath 2>$null
        if ($vsPath -and (Test-Path "$vsPath\VC\Tools\MSVC")) {
            $cl = Get-ChildItem "$vsPath\VC\Tools\MSVC" -Recurse -Filter "cl.exe" `
                    -ErrorAction SilentlyContinue |
                  Where-Object { $_.FullName -match "Hostx64\\x64" } |
                  Select-Object -First 1
            if ($cl) { return $cl }
        }
    }

    # Fallback: common installation paths (VS 2022 / 2019, full or Build Tools)
    $roots = @(
        "${env:ProgramFiles}\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC"
        "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC"
        "${env:ProgramFiles}\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC"
        "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
        "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC"
        "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC"
        "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC"
    )
    foreach ($root in $roots) {
        if (-not (Test-Path $root)) { continue }
        $cl = Get-ChildItem $root -Recurse -Filter "cl.exe" -ErrorAction SilentlyContinue |
              Where-Object { $_.FullName -match "Hostx64\\x64" } |
              Select-Object -First 1
        if ($cl) { return $cl }
    }
    return $null
}

$clExe = Find-ClExe

if (-not $clExe) {
    Write-Host "ERROR: cl.exe (MSVC C++ compiler) not found." -ForegroundColor Red
    Write-Host ""
    Write-Host "Please install one of:" -ForegroundColor Yellow
    Write-Host "  - Visual Studio 2022/2019 with 'Desktop development with C++' workload"
    Write-Host "  - Visual Studio Build Tools with 'MSVC v143 C++ x64/x86 build tools'"
    Write-Host "  Download: https://visualstudio.microsoft.com/downloads/"
    Write-Host ""
    exit 1
}

$nvccBin = $clExe.DirectoryName
Write-Host "  cl.exe : $($clExe.FullName)" -ForegroundColor Green

# ── 2. Verify CUDA ────────────────────────────────────────────────────────────

$cudaPath = $env:CUDA_PATH
if (-not $cudaPath) {
    Write-Host "  CUDA   : CUDA_PATH not set (nvcc may still work if on PATH)" -ForegroundColor Yellow
} else {
    Write-Host "  CUDA   : $cudaPath" -ForegroundColor Green
}

# ── 3. Write src-tauri/.cargo/config.toml ────────────────────────────────────
#
# Cargo's [env] table in config.toml is propagated to ALL build scripts,
# including candle-kernels' build.rs which calls nvcc. This avoids needing
# a VS Developer Command Prompt or modifying the system PATH.

$configDir  = Join-Path $PSScriptRoot "src-tauri\.cargo"
$configFile = Join-Path $configDir "config.toml"

if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir | Out-Null
}

# Escape backslashes for TOML string
$tomlPath = $nvccBin -replace "\\", "\\\\"

@"
# Auto-generated by setup-gpu-env.ps1 — machine-specific, do NOT commit.
# Tells nvcc where to find cl.exe so CUDA kernels can be compiled on Windows.
# Re-run setup-gpu-env.ps1 if you update Visual Studio.

[env]
NVCC_CCBIN = "$tomlPath"
"@ | Set-Content -Path $configFile -Encoding UTF8

Write-Host ""
Write-Host "Written: $configFile" -ForegroundColor Cyan
Write-Host ""
Write-Host "Setup complete. You can now run GPU builds from any terminal:" -ForegroundColor Green
Write-Host ""
Write-Host "  npm run tauri:dev:gpu    # development (hot-reload)"  -ForegroundColor Yellow
Write-Host "  npm run tauri:build:gpu  # release build"              -ForegroundColor Yellow
Write-Host ""
